# Generated by Django 6.0 on 2025-12-24 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='courses',
        ),
    ]
