# Generated by Django 6.0 on 2025-12-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_signup_v'),
    ]

    operations = [
        migrations.CreateModel(
            name='mycours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(default='General', max_length=100)),
                ('pub_date', models.DateField()),
                ('category', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
