# Generated by Django 6.0 on 2025-12-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_mycours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mycours',
        ),
        migrations.AlterField(
            model_name='signup_v',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
