# Generated by Django 6.0 on 2025-12-30 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_delete_mycours_alter_signup_v_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='mycours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.courses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.signup_v')),
            ],
        ),
    ]
